version: '3'
services:
  db:
    container_name: piper-db
    image: postgres:11.3-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: piper
    volumes:
      - ./data/db:/var/lib/postgresql/data

  web:
    build: .
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: "postgresql://postgres:secret@piper-db:5432/piper"
      DATABASE_ROLE: "postgres"
    depends_on:
      - db
